### PR TITLE
Set deviceId in Saved Command before sending

### LINKED ISSUE #3592: Error using saved commands
Hi Guys...I'm not sure if the saved commands feature implementation is complete but I get this error when I create a command and send it using this method. Sending same command using "custom command" works but not when it has been saved  using the "saved command" feature. Device protocol is gt06.
```
2017-10-19 23:53:11 DEBUG: [B6DC9A6C: 5023 < 172.56.10.160] HEX: 78780a13460602000200291cbd0d0a
2017-10-19 23:53:11 DEBUG: [B6DC9A6C: 5023 > 172.56.10.160] HEX: 78780513000a57220d0a
2017-10-19 23:53:11  INFO: [B6DC9A6C] id: 358899059057128, time: 2017-10-19 22:35:30, lat: 44.73917, lon: -93.36628, speed: 0.5, course: 332.0
2017-10-19 23:54:40  WARN: [B6DC9A6C] error - NullPointerException (BaseProtocolEncoder:28 < *:53 < ... < ActiveDevice:51 < BaseProtocol:76 < ...)
2017-10-19 23:54:40  INFO: [B6DC9A6C] disconnected
2017-10-19 23:54:45  INFO: [9A8FC3FE] connected
2017-10-19 23:54:45 DEBUG: [9A8FC3FE: 5023 < 172.56.10.160] HEX: 78780d010358899059057128002ab7f80d0a
2017-10-19 23:54:45 DEBUG: [9A8FC3FE: 5023 > 172.56.10.160] HEX: 787805010001d9dc0d0a
2017-10-19 23:54:46 DEBUG: [9A8FC3FE: 5023 < 172.56.10.160] HEX: 78780a134606020002002b3faf0d0a
2017-10-19 23:54:46 DEBUG: [9A8FC3FE: 5023 > 172.56.10.160] HEX: 787805130002db6a0d0a
2017-10-19 23:54:46  INFO: [9A8FC3FE] id: 358899059057128, time: 2017-10-19 22:35:30, lat: 44.73917, lon: -93.36628, speed: 0.5, course: 332.0
2017-10-19 23:54:46 DEBUG: [9A8FC3FE: 5023 < 172.56.10.160] HEX: 78781f12110a1403231ec404cccc480a0461a001dd4c01360474b1009cf7002c65e10d0a
2017-10-19 23:54:46 DEBUG: [9A8FC3FE: 5023 > 172.56.10.160] HEX: 787805120003903f0d0a
2017-10-19 23:54:46  INFO: [9A8FC3FE] id: 358899059057128, time: 2017-10-19 22:35:30, lat: 44.73917, lon: -93.36628, speed: 0.5, course: 332.0
2017-10-19 23:55:44  WARN: [9A8FC3FE] error - NullPointerException (BaseProtocolEncoder:28 < *:53 < ... < ActiveDevice:51 < BaseProtocol:76 < ...)
2017-10-19 23:55:44  INFO: [9A8FC3FE] disconnected
2017-10-19 23:55:49  INFO: [3E264C63] connected
2017-10-19 23:55:50 DEBUG: [3E264C63: 5023 < 172.56.10.160] HEX: 78780d010358899059057128002dc3470d0a
2017-10-19 23:55:50 DEBUG: [3E264C63: 5023 > 172.56.10.160] HEX: 787805010001d9dc0d0a
```

### PR DESCRIPTION
**Pull request by Abyss777**
We can't send bare Saved Command, we need to set `deviceId` in it before sending to log working correctly. Also we can't set `deviceId` in Saved Command to not change cached instance.

I decided just override incoming entity with cached Saved Command

Also optimized resource a bit.

fix #3592 

PS: tested with a real device

### CODE REVIEW

File: src/org/traccar/api/resource/CommandResource.java [hunk 1]
```diff
@@ -62,17 +62,14 @@ public Response send(Command entity) throws Exception {
...
             Context.getPermissionsManager().checkPermission(Command.class, getUserId(), id);
-            Context.getPermissionsManager().checkDevice(getUserId(), deviceId);
             Context.getPermissionsManager().checkUserDeviceCommand(getUserId(), deviceId, id);
-            sent = Context.getCommandsManager().sendCommand(id, deviceId);
         } else {
             Context.getPermissionsManager().checkLimitCommands(getUserId());
-            Context.getPermissionsManager().checkDevice(getUserId(), deviceId);
-            sent = Context.getCommandsManager().sendCommand(entity, deviceId);
         }
+        boolean sent = Context.getCommandsManager().sendCommand(entity);
```
Comment (tananaev) [inline src/org/traccar/api/resource/CommandResource.java]: Do we need variable here? We can probably just check result directly.

File: src/org/traccar/database/CommandsManager.java [hunk 2]
```diff
@@ -45,11 +45,15 @@ public boolean checkDeviceCommand(long deviceId, long commandId) {
...
 
-    public boolean sendCommand(long commandId, long deviceId) throws Exception {
-        return sendCommand(getById(commandId), deviceId);
-    }
-
-    public boolean sendCommand(Command command, long deviceId) throws Exception {
+    public boolean sendCommand(Command command) throws Exception {
+        long deviceId = command.getDeviceId();
+        if (command.getId() != 0) {
+            Command savedCommand = getById(command.getId());
```
Comment (tananaev) [inline src/org/traccar/database/CommandsManager.java]: Can we instead clone the object and set `deviceId`? Will be shorter and easier to manage. We won't need to modify the code in case we add something else to the command.

Comment (Abyss777) [reply src/org/traccar/database/CommandsManager.java]: There is no `clone()` by default. We should either implement interface `Cloneable` on `Command` or copying constructor.
Copying constructor also can just enumerate all setters (like here, but it will be in model and chance to miss something is less) or use reflection.

What do you prefer?

Comment (tananaev) [reply src/org/traccar/database/CommandsManager.java]: I think clone should work just fine here.

**Comment by Abyss777** [comment]
Implemented cloning and removed unneeded variables

File: src/org/traccar/model/Command.java [hunk 3]
```diff
@@ -77,6 +77,11 @@
     public static final String KEY_SERVER = "server";
     public static final String KEY_PORT = "port";
 
+    @Override
+    public Command clone() throws CloneNotSupportedException {
```
Comment (tananaev) [inline src/org/traccar/model/Command.java]: Do we really need this override? I suggest we just use default clone as it is.

Comment (Abyss777) [reply src/org/traccar/model/Command.java]: It is `protected` https://docs.oracle.com/javase/7/docs/api/java/lang/Object.html#clone()

Comment (tananaev) [reply src/org/traccar/model/Command.java]: I see. OK, can you then please fix indentation in this method.

**Comment by Abyss777** [comment]
Oh, sorry. Fixed indentation.

**Comment by tananaev** [comment]
Merged, thanks.
